Winnipeg-Open-Source/Main-Street-Project-FE

.env
.gitignore
package.json
src/components/FoodDonationForm/FoodDonationForm.js
src/components/FoodDonationForm/FoodDonationForm.spec.js
src/components/FoodDonationForm/FoodDonationForm.story.js
src/components/FoodDonationForm/index.js

Food Donation Form

---

package-lock.json
src/components/ClothesDonationForm/ClothesDonationForm.js
src/components/ClothesDonationForm/ClothesDonationForm.spec.js
src/components/ClothesDonationForm/ClothesDonationForm.story.js
src/components/ClothesDonationForm/__snapshots__/ClothesDonationForm.spec.js.snap
src/components/ClothesDonationForm/index.js
src/components/Form/Form.js
src/components/Form/Form.spec.js
src/components/Form/Form.story.js
src/components/Form/__snapshots__/Form.spec.js.snap
src/components/Form/index.js

Clothes Donation Form

---

src/components/HouseholdItemDonationForm/HouseholdItemDonationForm.js
src/components/HouseholdItemDonationForm/HouseholdItemDonationForm.spec.js
src/components/HouseholdItemDonationForm/HouseholdItemDonationForm.story.js
src/components/HouseholdItemDonationForm/__snapshots__/HouseholdItemDonationForm.spec.js.snap
src/components/HouseholdItemDonationForm/index.js

Household Item Donation Form

---

src/components/MiscellaneousDonationForm/MiscellaneousDonationForm.js
src/components/MiscellaneousDonationForm/MiscellaneousDonationForm.spec.js
src/components/MiscellaneousDonationForm/MiscellaneousDonationForm.story.js
src/components/MiscellaneousDonationForm/__snapshots__/MiscellaneousDonationForm.spec.js.snap
src/components/MiscellaneousDonationForm/index.js

Miscellaneous Donation Form

---

package.json
src/components/ButtonGroup/ButtonGroup.spec.js
src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.js.snap
src/components/Content/Content.spec.js
src/components/Content/__snapshots__/Content.spec.js.snap
src/components/Header/Header.js
src/components/Header/Header.spec.js
src/components/Header/__snapshots__/Header.spec.js.snap
src/components/Link/Link.spec.js
src/components/Link/__snapshots__/Link.spec.js.snap
src/components/Page/Page.js
src/components/Page/Page.spec.js
src/components/Page/Page.story.js
src/components/Page/__snapshots__/Page.spec.js.snap
src/components/Sidebar/Sidebar.spec.js
src/components/Sidebar/__snapshots__/Sidebar.spec.js.snap
src/hooks/useBreakpoint/useBreakpoint.spec.js

Added a bunch of tests getting coverage up to ~50%, will push it higher in a future PR

Improve Test Coverage

---

package-lock.json
src/components/ClothesDonationForm/ClothesDonationForm.js
src/components/ClothesDonationForm/ClothesDonationForm.spec.js
src/components/FoodDonationForm/FoodDonationForm.js
src/components/FoodDonationForm/FoodDonationForm.spec.js
src/components/Form/Form.js
src/components/HouseholdItemDonationForm/HouseholdItemDonationForm.js
src/components/HouseholdItemDonationForm/HouseholdItemDonationForm.spec.js
src/components/MiscellaneousDonationForm/MiscellaneousDonationForm.js
src/components/MiscellaneousDonationForm/MiscellaneousDonationForm.spec.js
src/components/NewItemDonationForm/NewItemDonationForm.js
src/components/NewItemDonationForm/NewItemDonationForm.spec.js
src/components/NewItemDonationForm/NewItemDonationForm.story.js
src/components/NewItemDonationForm/__snapshots__/NewItemDonationForm.spec.js.snap
src/components/NewItemDonationForm/index.js
src/tests/mocks/MockDonationFormProps.js

New Item Donation Form

---

src/components/DonationList/DonationList.js
src/hooks/useAxios/index.js
src/hooks/useAxios/useLocalAxios.js
src/pages/Donor/Donor.js
src/pages/Requisitions/Requisitions.js
src/reducers/RequisitionForm/RequisitionForm.js
src/tests/mocks/donations.js
src/tests/mocks/donors.js
src/tests/mocks/employees.js
src/tests/mocks/items.js
src/tests/mocks/requisitions.js

Mock out API calls for local development

---

src/actions/Donations/Donations.js
src/actions/Donations/index.js
src/constants/paths.js
src/containers/Routes/Routes.js
src/context/Donations/Donations.js
src/context/Donations/index.js
src/hooks/useDonation/index.js
src/hooks/useDonation/useDonation.js
src/hooks/useDonation/useDonation.spec.js
src/hooks/useDonations/index.js
src/hooks/useDonations/useDonations.js
src/hooks/useDonations/useDonations.spec.js
src/hooks/useDonationsReducer/index.js
src/hooks/useDonationsReducer/useDonationsReducer.js
src/hooks/useLoadDonations/index.js
src/hooks/useLoadDonations/useLoadDonations.js
src/pages/Donation/Donation.js
src/pages/Donation/Donation.story.js
src/pages/Donation/index.js
src/providers/Donations/Donations.js
src/providers/Donations/index.js
src/providers/Providers/Providers.js
src/reducers/Donations/Donations.js
src/reducers/Donations/index.js

Donation Page

---

src/components/DonationCard/DonationCard.js
src/components/DonationCard/DonationCard.spec.js
src/components/DonationCard/DonationCard.story.js
src/components/DonationCard/__snapshots__/DonationCard.spec.js.snap
src/components/DonationList/DonationList.js
src/components/DonationList/DonationList.story.js
src/components/DonationList/DonationListSkeleton.js
src/containers/Routes/Routes.js
src/pages/Donations/Donations.js
src/pages/Donations/Donations.story.js
src/pages/Donations/index.js
src/pages/Donor/Donor.spec.js
src/pages/Donor/__snapshots__/Donor.spec.js.snap
src/pages/Donors/Donors.js
src/tests/mocks/donations.js

Donations Page

---

src/constants/paths.js
src/constants/routes.js
src/containers/App/__snapshots__/App.spec.js.snap

Sidebar Icons and Nav

---

src/components/LinkButton/LinkButton.js
src/components/LinkButton/LinkButton.story.js
src/components/LinkButton/index.js
src/containers/Routes/Routes.js
src/pages/Items/Items.js
src/pages/Items/Items.story.js
src/pages/Items/index.js

Items Page

---

src/components/LocationCard/LocationCard.js
src/components/LocationCard/LocationCard.story.js
src/components/LocationCard/index.js
src/components/LocationForm/LocationForm.js
src/components/LocationForm/LocationForm.story.js
src/components/LocationForm/index.js
src/components/LocationsList/LocationsList.js
src/components/LocationsList/LocationsList.story.js
src/components/LocationsList/index.js
src/constants/paths.js
src/containers/LocationForm/LocationForm.js
src/containers/LocationForm/index.js
src/containers/LocationsList/LocationsList.js
src/containers/LocationsList/index.js
src/containers/Routes/Routes.js
src/hooks/context/useLocations/index.js
src/hooks/context/useLocations/useLocations.js
src/hooks/useAxios/useLocalAxios.js
src/pages/LocationCreate/LocationCreate.js
src/pages/LocationCreate/LocationCreate.story.js
src/pages/LocationCreate/index.js
src/pages/Locations/Locations.js
src/pages/Locations/Locations.story.js
src/pages/Locations/index.js
src/providers/Providers/Providers.js
src/reducers/Resources/Resources.js
src/tests/mocks/locations.js

Locations Pages

---

src/components/DonationCard/DonationCardSkeleton.js
src/components/DonorCard/DonorCardSkeleton.js
src/components/DonorCard/__snapshots__/DonorCard.spec.js.snap
src/components/DonorsList/__snapshots__/DonorsList.spec.js.snap
src/components/LocationCard/LocationCard.story.js
src/components/LocationCard/LocationCardSkeleton.js
src/components/LocationCard/index.js
src/components/LocationsList/LocationsList.story.js
src/components/LocationsList/LocationsListSkeleton.js
src/components/LocationsList/index.js
src/components/RequisitionCard/RequisitionCard.js
src/containers/LocationsList/LocationsList.js
src/pages/Donations/Donations.story.js
src/pages/Donor/__snapshots__/Donor.spec.js.snap
src/pages/Donors/Donors.story.js
src/pages/Donors/__snapshots__/Donors.spec.js.snap
src/pages/Items/Items.story.js
src/pages/Locations/Locations.story.js
src/pages/Requisitions/Requisitions.js

Location Loading and Improved Loading

---

src/components/DonationCard/DonationCard.js
src/components/DonationCard/__snapshots__/DonationCard.spec.js.snap
src/components/LocationCard/LocationCard.js
src/components/LocationCard/LocationCardSkeleton.js
src/components/LocationsList/LocationsList.js
src/pages/Locations/Locations.js

Locations Page - Not Found State

---

src/components/ItemCard/ItemCard.story.js
src/components/ItemCard/ItemCardSkeleton.js
src/components/ItemCard/index.js
src/components/ItemList/ItemList.js
src/components/ItemList/ItemList.story.js
src/components/ItemList/ItemListSkeleton.js
src/components/ItemList/index.js
src/pages/DonationCreate/__snapshots__/DonationCreate.spec.js.snap
src/pages/Donor/__snapshots__/Donor.spec.js.snap
src/pages/Items/Items.js
src/pages/RequisitionCreate/__snapshots__/RequisitionCreate.spec.js.snap

Items Page - Loading State

---

src/components/ItemList/ItemList.js
src/pages/DonationCreate/DonationCreate.js
src/pages/DonationCreate/DonationCreate.spec.js
src/pages/Items/Items.js

Items Page - Not Found State

---

functions/src/api/requisitions/requisitions.ts

Requisitions get and getAll APIs

---

functions/src/api/donations/donations.ts

Code complete for GET donations/:id and GET donations/ endpoints
modified:   functions/src/api/donations/donations.ts

API-66 Added additional donations endpoints

---

src/components/Collapse/Collapse.js
src/components/Collapse/__snapshots__/Collapse.spec.js.snap
src/components/DonationForm/DonationForm.js
src/components/DonationInformation/DonationInformation.js
src/components/DonationInformation/DonationInformation.story.js
src/components/DonationInformation/DonationInformationSkeleton.js
src/components/DonationInformation/index.js
src/components/DonorCreationForm/__snapshots__/DonorCreationForm.spec.js.snap
src/components/DonorInformation/DonorInformation.js
src/components/DonorInformation/DonorInformation.spec.js
src/components/DonorInformation/DonorInformation.story.js
src/components/Form/Form.js
src/components/Form/__snapshots__/Form.spec.js.snap
src/components/ItemCard/ItemCard.js
src/components/ItemForm/__snapshots__/ItemForm.spec.js.snap
src/components/ItemList/ItemList.js
src/components/LineItemCard/LineItemCard.js
src/pages/Donation/Donation.js
src/pages/Donation/Donation.story.js
src/pages/DonationCreate/__snapshots__/DonationCreate.spec.js.snap
src/pages/Donor/Donor.spec.js
src/pages/DonorCreate/__snapshots__/DonorCreate.spec.js.snap
src/pages/RequisitionCreate/__snapshots__/RequisitionCreate.spec.js.snap
src/tests/mocks/donations.js
src/tests/mocks/items.js

Create Donation Page

---

functions/src/api/authentication/authentication.ts
functions/src/utils/firebase/firebase.ts
src/containers/LoginForm/LoginForm.js
src/context/Authentication/Authentication.js
src/hooks/useLogin/useLogin.js
src/pages/Login/Login.js
src/reducers/Authentication/Authentication.js
src/reducers/Axios/Axios.js
src/reducers/Axios/Axios.spec.js

Fix Login Flow

---

src/constants/routes.js

- Update donors page to use different icon from users page
Closes #118

fix(118): Update nav bar icons
